name: Build and Deploy Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.100-preview.6'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Publish App
      run: dotnet publish -c Release -o publish

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t kidslearningplatform .

    - name: Run Docker Container
      run: docker run -d -p 8080:8080 kidslearningplatform
